#!/usr/bin/env bash

set -o xtrace
set -o errexit

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
CALL_DIR="$(pwd)"
cd "$SCRIPT_DIR"

# Check for dependencies
for dep in bash docker; do
    command -v ${dep} &>/dev/null || { echo "The command '${dep}' is required."; exit 1; }
done

# Build the jellyfin-ffmpeg portable version
[[ $(docker image ls 'ghcr.io/jellyfin/jellyfin-ffmpeg/linux64-gpl:latest' | wc -l) -eq 1 ]] && \
    ./makeimage.sh linux64 gpl

./build.sh linux64 gpl

# If no 1st parameter was specified, move pkg to parent directory
if [[ -z ${1} ]]; then
    path="${REPO_ROOT}/bin"
elif [[ ${1} = /* ]]; then
    path="${1}"
else
    path="${CALL_DIR}/${1}"
fi
mkdir -p "${path}"
mv artifacts/jellyfin-ffmpeg*portable_linux64-gpl*.tar.xz "${path}"
