#!/usr/bin/env bash

set -o xtrace
set -o errexit

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
CALL_DIR="$(pwd)"
cd "$SCRIPT_DIR"

# Check for dependencies
for dep in docker; do
    command -v ${dep} &>/dev/null || { echo "The command '${dep}' is required."; exit 1; }
done

base_image="ubuntu"
base_tag="noble"
image_name="jellyfin-ffmpeg-build-windows-win64"
package_temporary_dir="$( mktemp -d )"

# Trap cleanup for latter sections
cleanup() {
    # Remove tempdir
    rm -rf "${package_temporary_dir}"
}
trap cleanup EXIT INT

# Set up the build environment docker image
docker build \
    --build-arg BASE_IMAGE="${base_image}" \
    --build-arg BASE_TAG="${base_tag}" \
    --build-arg TARGETPLATFORM=linux/amd64 \
    -f "$SCRIPT_DIR/Dockerfile.win64.in" \
    -t "${image_name}" \
    "$REPO_ROOT"
# Build the APKs and copy out to ${package_temporary_dir}
docker run --rm -v "${package_temporary_dir}:/dist" "${image_name}"
# If no 1st parameter was specified, move APKs to parent directory
if [[ -z ${1} ]]; then
    path="${REPO_ROOT}/bin"
elif [[ ${1} = /* ]]; then
    path="${1}"
else
    path="${CALL_DIR}/${1}"
fi
mkdir -p "${path}"
mv "${package_temporary_dir}"/zip/jellyfin-ffmpeg*.zip "${path}"
