# Use a build argument for the base image
ARG BASE_IMAGE=debian:bookworm
FROM ${BASE_IMAGE}

# The target platform is automatically provided by Docker Buildx
ARG TARGETPLATFORM
ARG TARGETARCH

# Docker build arguments
ARG SOURCE_DIR=/ffmpeg
ARG ARTIFACT_DIR=/dist

# FFmpeg-specific environment
# These can be made dynamic based on TARGETARCH if needed, but for win64 cross-build it is standard
ENV FF_TOOLCHAIN=x86_64-w64-mingw32
ENV FF_CROSS_PREFIX=x86_64-w64-mingw32-
ENV FF_PREFIX=/usr/lib/jellyfin-ffmpeg
ENV FF_DEPS_PREFIX=/usr/${FF_TOOLCHAIN}
ENV FF_CMAKE_TOOLCHAIN=${SOURCE_DIR}/packaging/linux/toolchain-win64.cmake
ENV FF_MESON_TOOLCHAIN=${SOURCE_DIR}/packaging/linux/cross-win64.meson
ENV FF_TARGET_FLAGS="--arch=x86_64 --target-os=mingw32 --cross-prefix=${FF_CROSS_PREFIX} --pkg-config=pkg-config --pkg-config-flags=--static"

# Docker run environment
ENV DEBIAN_FRONTEND=noninteractive
ENV SOURCE_DIR=${SOURCE_DIR}
ENV ARTIFACT_DIR=${ARTIFACT_DIR}
ENV PATH=${FF_PREFIX}/bin:${PATH}
ENV PKG_CONFIG_PATH=${FF_DEPS_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}

# Prepare Debian build environment
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y apt-transport-https \
    curl ninja-build debhelper gnupg wget devscripts \
    mmv equivs git nasm pkg-config subversion dh-autoreconf \
    python3-pip zip unzip tar flex bison gperf ragel lsb-release \
    mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-mingw-w64 quilt \
 && apt-get clean autoclean -y \
 && apt-get autoremove -y

# Install newer tools from pip3
RUN pip3 install $(pip3 help install | grep -o "\-\-break-system-packages") --ignore-installed pip \
 && pip3 install $(pip3 help install | grep -o "\-\-break-system-packages") meson cmake mako jinja2 pyyaml

# Avoids timeouts when using git and disable the detachedHead advice
RUN git config --global http.postbuffer 524288000 \
 && git config --global advice.detachedHead false

# Copy the source code
COPY . ${SOURCE_DIR}/

# Prepare debian/ and builder/ for the build
RUN mkdir -p ${SOURCE_DIR}/debian && \
    cp -r ${SOURCE_DIR}/packaging/debian/* ${SOURCE_DIR}/debian/ && \
    mkdir -p ${SOURCE_DIR}/builder && \
    cp -r ${SOURCE_DIR}/packaging/portable/* ${SOURCE_DIR}/builder/

# Link to docker-build script
RUN ln -sf ${SOURCE_DIR}/packaging/windows/docker-build-win64.sh /docker-build.sh

VOLUME ${ARTIFACT_DIR}/

ENTRYPOINT ["/docker-build.sh"]
